stof_doctrine_extensions:
    class:
        timestampable: Gedmo\Timestampable\TimestampableListener
        sluggable: Gedmo\Sluggable\SluggableListener
    orm:
        default:
            timestampable: true
            sluggable: true